### ISSUE TITLE
Static network configuration

### ISSUE THREAD

**Issue by chapulina** [ignitionrobotics/ign-transport#129]
Kubernetes, and specifically the Weave network, has scaling problems. We have to use Weave because of multicast discovery in Ignition Transport. The goal is to remove the Weave requirement, and do so we need to get rid of the multicast requirement in Ignition Transport.

Our current thought is to add a static network configuration option to Ignition Transport. Cloudsim could, for example, explicitly tell Ignition Transport IP address of the network members.

**Comment by caguero** [comment]
In the absence of multicast, it's possible to use the environment variable `IGN_RELAY` to achieve a unicast discovery. It's not technically a static discovery but it solves the use case described in this issue.
