### ISSUE TITLE
Thread sync

### ISSUE THREAD

**Issue by ahoarau** [ignitionrobotics/ign-transport#197]
Hello all !
Is there an equivalent to the ROS `ros::spinOnce()` that allows synchronization between ignition event loop and a different thread ?
For example in `rviz`, all ros callbacks are called synced with the qt event loop. Is there a way to do the same with ign-transport ?
Thanks a bunch !

**Comment by caguero** [comment]
Hi @ahoarau , there's nothing similar in Ignition Transport. The event thread is running as fast as possible without being able to control it externally.
