### ISSUE TITLE
Deprecated use of zmq::poll

### ISSUE THREAD

**Issue by jacobperron** [ignitionrobotics/ign-transport#261]
## Environment
* OS Version: macOS 
* Source or binary build?
  Source (branches `ign-transport8` and `ign-transport10`, probably `ign-transport9`)

## Description

* Expected behavior: No deprecation warnings during build
* Actual behavior: Deprecation warnings

## Steps to reproduce

See https://build.osrfoundation.org/job/ignition_transport-ci-ign-transport10-homebrew-amd64/6/

Also happening on Citadel and probably Dome:

- https://build.osrfoundation.org/job/ignition_transport-ci-ign-transport8-homebrew-amd64/38/clang/

## Output

```
'poll' is deprecated: from 4.8.0, use poll taking std::chrono::duration instead of long
```

Coming from `NodeShared.cc` and `Discovery.cc`

**Comment by Blast545** [comment]
This was addressed indirectly in main with #265 and directly for Citadel + onward with #268 #269 #270. Closing
