### ISSUE TITLE
Topic and Serivce list error 

### ISSUE THREAD

**Issue by ggiulian** [ignitionrobotics/ign-transport#276]
## Environment
* OS Version: Ubuntu 20.04 
* Source or binary build?
  Source: Ignition Edifice and Galactic

Since the last ign-transport update, whenever I run on the command line: `ign topic -l` or `ign service`, I find this error: 

 
```
Traceback (most recent call last):
	2: from /usr/bin/ign:308:in `<main>'
	1: from /usr/lib/ruby/ignition/cmdtransport10.rb:43:in `execute'
/usr/lib/ruby/ignition/cmdtransport10.rb:43:in ``': No such file or directory - /usr/lib/x86_64-linux-gnu/ignition/transport10/ign-transport-service (Errno::ENOENT)
```
```
Traceback (most recent call last):
	2: from /usr/bin/ign:308:in `<main>'
	1: from /usr/lib/ruby/ignition/cmdtransport10.rb:43:in `execute'
/usr/lib/ruby/ignition/cmdtransport10.rb:43:in ``': No such file or directory - /usr/lib/x86_64-linux-gnu/ignition/transport10/ign-transport-topic (Errno::ENOENT)

```

## Description
* Expected behavior: list of topic and service
* Actual behavior: error

**Comment by chapulina** [comment]
I think this should have been fixed by https://github.com/ignition-release/ign-transport10-release/pull/6

@ggiulian , what version of `ign-transport` are you using? Can you try installing the binaries from packages.osrfoundation.org as instructed here? https://ignitionrobotics.org/docs/edifice/install_ubuntu

**Comment by ggiulian** [comment]
I installed the Edifice from binaries. Same result. The transport version is 10

**Comment by chapulina** [comment]
Ok, I thought that a release had been triggered after ignition-release/ign-transport10-release#6 was merged, but it wasn't. I can reproduce the issue. I just triggered a new release, you can check the status here: https://build.osrfoundation.org/job/ign-transport10-debbuilder/

**Comment by ggiulian** [comment]
Hi, a little update, now the `ign topic` and `ign service` commands work. Thanks
