### ISSUE TITLE
ign-transport doesn't exit cleanly in MATLAB in Windows

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-transport#30]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-transport/issues/30)) by Brian Gerkey (Bitbucket: [Brian Gerkey](https://bitbucket.org/%7B3d8b5763-9dad-4be7-85c2-a7ab6cd49173%7D/), GitHub: [gerkey](https://github.com/gerkey)).**

----------------------------------------
Originally a [haptix-comm issue](https://bitbucket.org/osrf/haptix-comm/issue/10), worked around for now via [PR58](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-transport/pull-request/58).

We should eventually figure out and fix the underlying issue.

**Comment by chapulina** [comment]
Closing this since I believe it would be difficult to reproduce now that HAPTIX has been deprecated for a long time. Please reopen if there's more information on how to reproduce the issue with currently supported `ign-transport` versions.
