### ISSUE TITLE
Consider appveyor for free Windows CI

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-transport#36]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-transport/issues/36)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/), GitHub: [scpeters](https://github.com/scpeters)).**

----------------------------------------
We are using it successfully in `ignition-math`:

* https://github.com/ignitionrobotics/ign-math/blob/master/appveyor.yml
* https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-math/commits/branch/default

It's also automatically displayed in the bitbucket build status API.

**Comment by chapulina** [comment]
@caguero / @scpeters , are you still considering Appveyor? Maybe GitHub actions would be a better option now?

**Comment by caguero** [comment]
Do GitHub actions support Windows?

**Comment by scpeters** [comment]
> Do GitHub actions support Windows?

yes they do

**Comment by caguero** [comment]
Then, let's use GitHub actions instead!
