### ISSUE TITLE
Topic info command line doesn't list subscribers

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-transport#39]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-transport/issues/39)) by Louise Poubel (Bitbucket: [chapulina](https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/), GitHub: [chapulina](https://github.com/chapulina)).**

----------------------------------------
To reproduce:

1.    Compile examples

1.    Start publisher, it publishes HELLO messages

1.    Start subscriber, it receives HELLO messages

1.    Check topic info with ign topic -i -t /foo and we see the publisher, but not the subscriber.

**Comment by chapulina** [comment]
Duplicate of #263
